### ISSUE TITLE
求助：配置工具检测不到键盘

### ISSUE THREAD

**Issue by Poplar-hills** [Lotlab/lkb-configurator#14]
BLE60键盘通过数据线链接电脑后在配置工具里检测不到，提示如下，刷新多次、多次更换过接口、切换 wifi 和热点都不行，”已连接设备“列表一直是空，终端中不断提示 `The operation has timed out`。

```
❯ ./lkb-configurator-server
欢迎使用 Lotlab 键盘配置工具
当前版本: 1.0.4.0, 正在检查更新……
当前使用的是最新版本
请使用浏览器访问  https://keyboard.lotlab.org 配置你的键盘。配置过程中请勿关闭此窗口。
System.TimeoutException: The operation has timed out.
   at HidSharp.AsyncResult`1.EndOperation()
   at HidSharp.AsyncResult`1.EndOperation(IAsyncResult asyncResult)
   at HidSharp.DeviceStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__45_1(Stream , IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance , Func`3 , IAsyncResult , Boolean )
--- End of stack trace from previous location ---
   at lkb_configurator_server.Models.KeyboardDeviceHID.HIDRequest(HidCommand command, Byte[] data, Int32 retry)
   at lkb_configurator_server.Models.KeyboardDeviceHID.GetInfo()
   at lkb_configurator_server.Models.KeyboardDeviceHID.SetDevice(HidDevice device)
   at lkb_configurator_server.Models.HIDDevices.ReloadHIDListAsync()
System.TimeoutException: The operation has timed out.
   at HidSharp.AsyncResult`1.EndOperation()
   at HidSharp.AsyncResult`1.EndOperation(IAsyncResult asyncResult)
   at HidSharp.DeviceStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__45_1(Stream , IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance , Func`3 , IAsyncResult , Boolean )
--- End of stack trace from previous location ---
   at lkb_configurator_server.Models.KeyboardDeviceHID.HIDRequest(HidCommand command, Byte[] data, Int32 retry)
   at lkb_configurator_server.Models.KeyboardDeviceHID.GetInfo()
   at lkb_configurator_server.Models.KeyboardDeviceHID.SetDevice(HidDevice device)
   at lkb_configurator_server.Models.HIDDevices.ReloadHIDListAsync()
```

**Comment by jim-kirisame** [comment]
USB访问键盘超时了，换个端口/设备试试
