### ISSUE TITLE
1.0.6.0 can't work

### ISSUE THREAD

**Issue by vagetablechicken** [Lotlab/lkb-configurator#16]
1.0.6.0 on win-64, got error:
```
The input string 'v1' was not in a correct format.
...
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN73O0278HUA", Request id "0HN73O0278HUA:00000007": An unhandled exception was thrown by the application.
      System.NotSupportedException: JsonTypeInfo metadata for type 'System.Byte[]' was not provided by TypeInfoResolver of type 'lkb_configurator_server.MyContext'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type, IJsonTypeInfoResolver)
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean , Nullable`1 , Boolean , Boolean )
         at System.Text.Json.JsonSerializerOptions.GetTypeInfo(Type)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1)
```

1.0.5.0 is ok, I can config keyboard properly.

**Comment by jim-kirisame** [comment]
fixed in v1.0.6.1
