### ISSUE TITLE
lkb-configurator-server shows exception

### ISSUE THREAD

**Issue by lightingghost** [Lotlab/lkb-configurator#3]
I was trying to run lkb-configurator-server on macOS 10.15.4, but got the following exception on the server side:

```
欢迎使用 Lotlab 键盘配置工具
当前版本: 0.9.9.10, 正在检查更新……
当前使用的是最新版本
请使用浏览器访问  https://keyboard.lotlab.org 配置你的键盘。配置过程中请勿关闭此窗口。
System.TimeoutException: The operation has timed out.
   at lkb_configurator_server.Models.KeyboardDeviceHID.HIDRequest(HidCommand command, Byte[] data, Int32 retry)
   at lkb_configurator_server.Models.KeyboardDeviceHID.GetInfo()
   at lkb_configurator_server.Models.KeyboardDeviceHID.SetDevice(HidDevice device)
   at lkb_configurator_server.Models.HIDDevices.ReloadHIDListAsync()
```

**Comment by jim-kirisame** [comment]
Please try another USB port. It seems that it is not working on some USB HUB
